#!/usr/bin/env bash

config_dir="$HOME/.config/rclone/rclone.conf"
options="/tmp/options"

rm -f "$options"
grep -o '\[[^][]*\]' "$config_dir" | sed 's/\[\|\]//g' >> "$options"
echo "quit" >> "$options"
echo "all" >> "$options"

print_usage() {
    cat <<-EOF
Usage:  gdrive mount [users]
        gdrive mount all
        gdrive quit

Mount Google Drive using rclone.

Commands:
    mount     Mount Google Drive for a specific users or mount all users.
    quit      Terminate all existing rclone processes.

Available Users:
$(grep -v -e '^quit$' -e '^all$' "$options")

Note: Use one of the available users from the options list or "all" to mount all users.
EOF
}

if [[ $# -eq 0 ]]; then
    print_usage
    exit 1
fi

command="$1"

case "$command" in
    "quit")
        pkill -f "rclone"
        ;;
    "mount")
        if [[ $# -lt 2 ]]; then
            cat <<-EOF
Please provide a users!

Users Available:
$(grep -v -e '^quit$' -e '^all$' "$options")
EOF
            exit 1
        fi
        users="$2"
        if [[ "$users" == "all" ]]; then
            while IFS= read -r line || [[ -n "$line" ]]; do
                if [[ "$line" != "quit" && "$line" != "all" ]]; then
                    rclone mount --daemon "$line": "$HOME/Google-Drive/$line" &
                fi
            done < "$options"
        else
            valid_options=$(grep -v -e '^quit$' -e '^all$' "$options")
                if [[ "$valid_options" == *"$users"* ]]; then
                    rclone mount --daemon "$users": "$HOME/Google-Drive/$users" &
                else
                    echo "Invalid user! Available users:"
                    echo "$valid_options"
                    exit 1
                fi
        fi
        ;;
    *)
        echo "Invalid command. Use 'mount' or 'quit'."
        exit 1
        ;;
esac
